AppBundle\Entity\MessageTranslation:
    type: entity
    table: message_translation
    repositoryClass: AppBundle\Repository\MessageTranslationRepository
    uniqueConstraints:
        uk_unq_key:
            columns:
                - message_domain_id
                - message_language_id
                - message_key_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        messageDomainId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: message_domain_id
        messageLanguageId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: message_language_id
        messageKeyId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: message_key_id
        messageText:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: message_text
        createdAt:
            type: datetime
            nullable: false
            comment: ''
            default: CURRENT_TIMESTAMP
            column: created_at
    lifecycleCallbacks: {  }
